version: '3.8'

services:
  web:
    container_name: sber-web
    build: .
    command: uvicorn service:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: on-failure